# Tuples

In [1]:
my_tup = (1,2,3,4)

In [2]:
my_tup[0]

1

In [3]:
my_tup[-1]

4

In [4]:
my_tup2 = ('a', 'b','c','d',5)

In [6]:
my_tup2[2]

'c'

In [7]:
my_tup2[2] = 'm'

TypeError: 'tuple' object does not support item assignment

In [9]:
my_tup2[::-1]

(5, 'd', 'c', 'b', 'a')

In [10]:
my_tup2.count('c')

1

In [11]:
my_tup2.count('f')

0

In [13]:
my_tup2

('a', 'b', 'c', 'd', 5)

In [12]:
my_tup2.index('b')

1

In [14]:
mylist = ['a',1,2,'AIR']

In [16]:
my_tup3 = tuple(mylist)

In [17]:
my_tup3

('a', 1, 2, 'AIR')

In [18]:
my_tup2

('a', 'b', 'c', 'd', 5)

In [20]:
new_list = list(my_tup2)

In [21]:
new_list

['a', 'b', 'c', 'd', 5]

In [22]:
my_tup4 = ()

In [30]:
len(my_tup4)

0

In [27]:
my_tup5 = (5)

In [29]:
type(my_tup5)

int

In [31]:
my_tup = (5,)

In [34]:
type(my_tup)

tuple

# Boolean

In [37]:
True

True

In [38]:
False

False

In [36]:
true

NameError: name 'true' is not defined

In [39]:
a = True

In [40]:
type(a)

bool

In [41]:
a = 0 #False in boolean
b = 15 #True in boolean

In [42]:
bool(a)

False

In [43]:
bool(b)

True

In [44]:
bool(16)

True

In [45]:
bool(50)

True

In [46]:
bool(15.6)

True

In [47]:
bool(0)

False

In [48]:
bool('mystring')

True

# Logic

In [49]:
a = 1
b = 5

In [50]:
a == b

False

In [51]:
1 == 1

True

In [52]:
2 == 2

True

In [53]:
2 == 3

False

In [54]:
a = 1
b = 5

In [55]:
a != b

True

In [56]:
a =! b

In [57]:
a

["'b' is not recognized as an internal or external command,",
 'operable program or batch file.']

In [58]:
a <> b

SyntaxError: invalid syntax (<ipython-input-58-7450b63d9fd5>, line 1)

In [59]:
a != b #barabar naboodan

True

In [61]:
a == b #barabar boodan

False

In [62]:
3 > 2

True

In [63]:
3 < 2

False

In [64]:
3 > 3

False

In [65]:
3 >= 3

True

In [66]:
# and , or

In [69]:
a = 3 > 2
print(a)

True


In [71]:
b = 15<= 45
print(b)

True


In [72]:
#and : if both are true
#or  : if at least one is true

In [74]:
5>4 and 8<16

True

In [75]:
5>4 and 8>16

False

In [77]:
True and True

True

In [78]:
True or True

True

In [82]:
True and True and True and True and 5<1

False

In [83]:
# in, is, not

In [84]:
'm' in 'My name is Milad'

True

In [85]:
type('m' in 'My name is Milad')

bool

In [86]:
'a' in ['a','b',[4,5,6],5 ,'7']

True

In [87]:
'c' in ['a','b',[4,5,6],5 ,'7']

False

In [88]:
5 in ['a','b',[4,5,6],5 ,'7']

True

In [89]:
4 in ['a','b',[4,5,6],5 ,'7']

False

In [90]:
#is

In [91]:
l1 = [1,2,3,4]
l2 = [1,2,3,4]
l3 = l1
l4 = l1.copy()

In [92]:
5 == 5

True

In [94]:
l1 == l2

True

In [95]:
l1 is l2

False

In [96]:
l1 is l3

True

In [97]:
l1 is l4

False

In [108]:
not True

False

In [109]:
l1 is not l4

True

In [111]:
all([True, True])

True

In [112]:
all([True, True, False])

False

In [113]:
any([True, True, False])

True

# Zip, Enumerate

## Zip

In [114]:
x = ['a','b','c','d']
y = ['x','y','z','o']

In [115]:
x

['a', 'b', 'c', 'd']

In [116]:
y

['x', 'y', 'z', 'o']

In [117]:
zip(x,y)

In [120]:
list(zip(x,y))

[('a', 'x'), ('b', 'y'), ('c', 'z'), ('d', 'o')]

In [121]:
z = [5,6,10,15]

In [123]:
list(zip(x,y,z))

[('a', 'x', 5), ('b', 'y', 6), ('c', 'z', 10), ('d', 'o', 15)]

In [126]:
x = [0,1,2,3]
y = ['x','y','z','o']
list(zip(x,y))

[(0, 'x'), (1, 'y'), (2, 'z'), (3, 'o')]

## Enumerate

In [128]:
y = ['x','y','z','o']
list(enumerate(y))

[(0, 'x'), (1, 'y'), (2, 'z'), (3, 'o')]

# List Comprehention

In [129]:
A = [1,2,3,5,10,15,200]

In [130]:
# in for

In [131]:
B = [n**2 for n in A] 

In [133]:
B

[1, 4, 9, 25, 100, 225, 40000]

In [135]:
[asghar**3 for asghar in A] 

[1, 8, 27, 125, 1000, 3375, 8000000]

In [136]:
[ _**3 for _ in A] 

[1, 8, 27, 125, 1000, 3375, 8000000]

In [143]:
[n**2 for n in range(10)]

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [144]:
[n**2 for n in list(range(10))]

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [145]:
from math import sqrt

In [147]:
[n**0.5 for n in range(6)]

[0.0, 1.0, 1.4142135623730951, 1.7320508075688772, 2.0, 2.23606797749979]

In [150]:
[10*sqrt(n) for n in range(6)]

[0.0, 10.0, 14.142135623730951, 17.32050807568877, 20.0, 22.360679774997898]

In [155]:
A = [6,7,8,9,10]
B = [1,10,25,0,7]

In [156]:
list(zip(A,B))

[(6, 1), (7, 10), (8, 25), (9, 0), (10, 7)]

In [157]:
c = [a-b for a,b in list(zip(A,B))] 

In [158]:
c

[5, -3, -17, 9, 3]

In [160]:
list(zip(A,B))[0]

(6, 1)

In [161]:
[n for n in list(zip(A,B))] 

[(6, 1), (7, 10), (8, 25), (9, 0), (10, 7)]

In [168]:
import numpy as np

In [170]:
A = np.array([2,5,7,6,15])
B = np.array([1,5,6,12,11])

In [172]:
B

array([ 1,  5,  6, 12, 11])

In [173]:
A

array([ 2,  5,  7,  6, 15])

In [174]:
A - B

array([ 1,  0,  1, -6,  4])

In [175]:
A*B

array([  2,  25,  42,  72, 165])

In [176]:
A + B

array([ 3, 10, 13, 18, 26])

In [177]:
A ** B

array([          2,        3125,      117649, -2118184960,  -308274769],
      dtype=int32)